version: '3'
services:
  redis:
    image: redis:6.2.1
    container_name: db-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis/config:/docker/config
      - ./redis/data:/data
    command: redis-server /docker/config/redis.conf